Vagrant.configure("2") do |config|
  config.vm.define "xenial32" do |xenial32|
    xenial32.vm.box = "ubuntu/xenial32"
    xenial32.vm.hostname = 'xenial32'
    xenial32.vm.box_url = "ubuntu/xenial32"

    xenial32.vm.network :private_network, ip: "192.168.56.101"
    xenial32.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"


    xenial32.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "ubuntu32"]
    end
	#config.vm.provision "shell", inline: <<-SHELL
	#	sudo apt-get update
	#	sudo apt-get install -y puppetxenial32
	#SHELL
  end
end

