Vagrant.configure("2") do |config|
  config.vm.define "xenial64" do |xenial64|
    xenial64.vm.box = "ubuntu/xenial64"
    xenial64.vm.hostname = 'xenial64'
    xenial64.vm.box_url = "ubuntu/xenial64"

    xenial64.vm.network :private_network, ip: "192.168.56.101"
    xenial64.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"


    xenial64.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web"]
    end
	#config.vm.provision "shell", inline: <<-SHELL
	#	sudo apt-get update
	#	sudo apt-get install -y puppetxenial64
	#SHELL
  end
end

